### ISSUE TITLE
`"` undefined behaviour

### ISSUE THREAD

**Issue by blyxyas** [qexat/Braincum#13]
> `"`: stringifies the value/address and changes to its ordinal.

What happens in the value is a double digit number? What happens with 10?

**Comment by qexat** [comment]
Well Python raises a ValueError lol
I know this issue came to my mind once during the conception of the specs but I forgor 💀

**Comment by qexat** [comment]
A way to fix it could be to get the ordinal of each character and sum them

**Comment by blyxyas** [comment]
I was going to propose a PR, but summing the ordinal of each number wouldn't be practical because that would mean that "33" is 102, and `$(33)"` would display "f"

Maybe disallow a case where the value is greater than 10, and the user has to display the number in multiple cells (like `[3, 3]`) so the interpreter can print the real number (using `"&+"`)

**Comment by qexat** [comment]
> I was going to propose a PR, but summing the ordinal of each number wouldn't be practical because that would mean that "33" is 102, and `$(33)"` would display "f"
> 
> 
> 
> Maybe disallow a case where the value is greater than 10, and the user has to display the number in multiple cells (like `[3, 3]`) so the interpreter can print the real number (using `"&+"`)

Interesting solution. I was also thinking of moving the overflow to the next cell, so [33] would lead to [51, 51]. This has the advantage to match the behavior of `:`, imo.

**Comment by blyxyas** [comment]
Ok implementing this rn!
