### ISSUE TITLE
[ Question ] What does it mean the following line in `spec.md`

### ISSUE THREAD

**Issue by blyxyas** [qexat/Braincum#3]
>
> `@`:
>    * value: sets to address % 255
>

What's doing the percentage symbol in that case? Is the address operated under the modulo operator? Is the address a maximum of 255?

**Comment by qexat** [comment]
> > `@`:
> > 
> > * value: sets to address % 255
> 
> What's doing the percentage symbol in that case? Is the address operated under the modulo operator? Is the address a maximum of 255?

Yes, it's the modulo operator.

Theorically, the cell table is infinite, which means that `address` can be very big ; however, a cell can only contain a value between 0x00 (0) and 0xFF (255), so I decided that it would be `address` modulo 255 to avoid value inconsistency (aka a value that is above 255).

Also, if you have other questions, please consider using the Discussions tab instead. Thanks in advance.
