### ISSUE TITLE
Documentation unclear ("Specifiable"/"Unspecifiable")

### ISSUE THREAD

**Issue by qexat** [qexat/Braincum#6]
This needs a fix.
The titles are pretty confusing and not really representative of what they are expected to mean: operators that are "specifiable", are actually operators that require a subject specifier (such as `&` or `$`)

**Comment by blyxyas** [comment]
maybe changing it with: "With subject required"?

**Comment by qexat** [comment]
> maybe changing it with: "With subject required" and "Without subject required"?

I plan to do something like that, yeah

**Comment by qexat** [comment]
@blyxyas by the way, if you'd like to make the PR (to `main`), I'll gladly merge it.

**Comment by blyxyas** [comment]
I'm working on a compiler as a side project, and tho I have some ideas I think I'll create a discussion about this so we don't fill out an issue.
